### ISSUE TITLE
Mailgun Routes Quota Exceeded

### ISSUE THREAD

**Issue by rishabnayak** [Bostonhacks/squadra#84]
All CI jobs from here on out will fail because we have exceeded the Mailgun routes quota? Someone needs to take a look at our Mailgun subscription tier and fix this :?

**Comment by ROODAY** [comment]
# [sendgrid babyyyyyyyy](https://github.com/Bostonhacks/inviare)

![bitmoji](https://sdk.bitmoji.com/render/panel/9bcdfb3d-0309-4259-8994-bb899ab7573a-8f093809-efd0-455a-8eea-d1e5a41569ee-v1.png?transparent=1&palette=1&width=246)
